export {
  DEFAULT_EMAIL_THEME,
  EMAIL_BLOCK_CATALOG,
  EMAIL_COLUMN_LAYOUTS,
  EMAIL_CONTAINER_BLOCK_TYPES,
  EMAIL_DOCUMENT_VERSION,
  EMAIL_HTML_BLOCK_MAX_BYTES,
  EMAIL_MERGE_TAGS,
} from './constants';
export { canPlaceEmailBlock, createEmailBlock, createEmailDocument, normalizeEmailDocument, walkEmailBlocks } from './factory';
export { EMAIL_PRESETS } from './presets';
export { renderEmailHtml } from './render';
export {
  EmailValidationError,
  assertValidEmailDocument,
  validateEmailDocument,
} from './validation';
export type {
  CreateEmailDocumentInput,
  EmailAlign,
  EmailBlock,
  EmailBlockCatalogItem,
  EmailBlockOfType,
  EmailBlockPropsMap,
  EmailBlockType,
  EmailButtonProps,
  EmailColumnsLayout,
  EmailColumnsProps,
  EmailContainerBlockType,
  EmailCouponProps,
  EmailDividerProps,
  EmailDocument,
  EmailDocumentVersion,
  EmailFooterProps,
  EmailHeadingProps,
  EmailHtmlProps,
  EmailImageProps,
  EmailLeafBlockType,
  EmailLink,
  EmailLogoProps,
  EmailMenuProps,
  EmailMenuSeparator,
  EmailMergeData,
  EmailMergeTag,
  EmailPreset,
  EmailProductProps,
  EmailSectionProps,
  EmailSocialLink,
  EmailSocialNetwork,
  EmailSocialProps,
  EmailSpacerProps,
  EmailSpacing,
  EmailTextProps,
  EmailTheme,
  EmailValidationIssue,
  EmailVerticalAlign,
  EmailVideoProps,
  RenderEmailOptions,
} from './types';
